### ISSUE TITLE
Passing timestamps doesn't work

### ISSUE THREAD

**Issue by norbertstoll** [puppetlabs/Puppet.Dsc#205]
## Describe the Bug
We're trying to create a scheduled task via [ScheduledTask resource](https://github.com/dsccommunity/ComputerManagementDsc) but we can't find the right syntax to get it work:

`Error: Failed to apply catalog: Parameter dsc_starttime failed on Dsc_scheduledtask[TEST]: dsc_scheduledtask.dsc_starttime expects a value of type Undef or Timestamp, got String`

## Expected Behavior
Since [PARAMETER StartTime  of DSC_ScheduledTask.psm1](https://github.com/dsccommunity/ComputerManagementDsc/blob/main/source/DSCResources/DSC_ScheduledTask/DSC_ScheduledTask.psm1) expects _datetime_ the following string should be accepted

_'2022/01/31 12:00:00'_

as it's valid PowerShell syntax:

```powershell 
PS C:\> [datetime]'2022/01/31 12:00:00'
Montag, 31. Januar 2022 12:00:00
```

This way it's working via DSC in its native way, too:
```powershell
Configuration TESTING {
        
    Import-DscResource -ModuleName computermanagementdsc

    Node localhost {
    
        ScheduledTask "TEST"

            {
                TaskName = "Hans1"
                Actionexecutable = 'C:\windows\system32\WindowsPowerShell\v1.0\powershell.exe'
                Actionarguments = '-noprofile -command "TEST"'
                Scheduletype = 'Daily'
                StartTime = '2022/01/31 12:00:00'
                User = 'SYSTEM'
                Enable = $true
                Ensure = "Present"
            }
        }
}
```

## Steps to Reproduce
1. Define via hiera and start a puppet run
```yaml
profile::dsc::computermanagement::scheduledtask:
  'TEST':
    dsc_taskname: 'TEST'
    dsc_taskpath: '\noris'
    dsc_actionexecutable: 'C:\windows\system32\WindowsPowerShell\v1.0\powershell.exe'
    dsc_actionarguments: '-noprofile -command "Test.ps1"'
    dsc_scheduletype: 'Daily'
    dsc_starttime: '2022/01/31 12:00:00'
    dsc_user: 'SYSTEM'
    dsc_enable: true
    dsc_ensure: Present
```

## Environment
`mod 'puppetlabs-pwshlib', '0.10.1'`
`mod 'dsc-computermanagementdsc', '8.5.0-0-0'`
Puppet Agent 6.25.0

## Additional Context
Seems like this has been an issue of puppetlabs-dsc in the past, too :
https://tickets.puppetlabs.com/browse/MODULES-5623
https://github.com/puppetlabs/puppetlabs-dsc/pull/371/commits/828aba1d700765c15a53c69e8b27ada697abc361

**Comment by michaeltlombardi** [comment]
What you're running into is the difference between what _DSC_ accepts and what _Puppet_ expects. The [definition for the `dsc_starttime` parameter is that the data type is `Optional[Timestamp]`](https://forge.puppet.com/modules/dsc/computermanagementdsc/reference#dsc_starttime).

2022/01/31 12:00:00'

In a Puppet manifest, [a timestamp is declared like this: `Timestamp['2022-01-31T12:00:00.000'] `](https://puppet.com/docs/puppet/7/lang_data_time.html#lang_data_time_timestamp).

You could also use the [conversion helpers in the Puppet language to convert from a string to a timestamp](https://puppet.com/docs/puppet/7/function.html#conversion-to-timestamp).

**Comment by chelnak** [comment]
Closing as this issue/question has been addressed.

**Comment by BarnumD** [comment]
I'm still experiencing this with `dsc-computermanagementdsc` `8.5.0-0-2`.  How was it addressed?
